sudo: required
services:
    - docker

before_install:
    - docker build -t kunalseth/react-test -f ./client/Dockerfile.dev ./client


script:
    - docker run kunalseth/react-test npm test -- --coverage


after_success:
    - docker build -t kunalseth/multi-client ./client
    - docker build -t kunalseth/multi-nginx ./nginx
    - docker build -t kunalseth/multi-server ./server
    - docker build -t kunalseth/multi-worker ./worker

    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #take images and push to docker hub
    - docker push kunalseth/multi-client
    - docker push kunalseth/multi-nginx
    - docker push kunalseth/multi-server
    - docker push kunalseth/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-757447646994
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY